Make external tests for MAGIC optional
scverse/scanpy pull request #1003
Opened 2020-01-21 15:40 UTC by scottgigante

Closes #1001

2020-01-21 15:48 UTC, scottgigante commented
Realised there's a better way of doing this with pytest.

2020-01-22 11:36 UTC, flying-sheep requested changes
Thank you for your quick response. The `tuple` stuff is a bit flaky though, let’s just use standard version parsing and comparing

2020-01-22 11:36 UTC, flying-sheep commented on scanpy/external/pp/_magic.py
> +__min_version__ = "2.0"
Don’t use `__dunder__` naming for things that aren’t standardized python names. You can just use `UPPER_WITH_UNDERSCORES` for constants.

2020-01-22 11:36 UTC, flying-sheep commented on scanpy/external/pp/_magic.py
>          if not version >= min_version:
Please compare versions using `packaging.version`

https://github.com/theislab/scanpy/blob/0d44d1d50138e76bdc120cfacfd40c222e47b79e/scanpy/external/tl/_pypairs.py#L150-L152

2020-01-22 15:17 UTC, scottgigante commented
Thanks, I hadn't seen `packaging.version` before. Much better!

2020-01-22 15:21 UTC, flying-sheep commented
It’s a recent change, driven by the complex stuff people did to compare versions :wink:

2020-01-22 15:21 UTC, flying-sheep approved these changes

2020-01-22 15:56 UTC, scottgigante commented
It's not clear to me why these `test_10x` tests are failing here and not on master -- there shouldn't be anything in this diff that affects those tests.

2020-01-22 16:34 UTC, flying-sheep commented
You’re right: They would be failing on master if master had been tested since anndata 0.7 was released earlier today. We have to merge #1004 to get tests to pass again before we can merge this.

2020-01-22 16:51 UTC, merged