Changing scanpy.pl.dotplot to return the matplotlib figure instead of GridSpec
scverse/scanpy pull request #1069
Opened 2020-02-21 22:22 UTC by atarashansky

Fixes issue #979 

Note that if you wish to modify the figure in the same jupyter notebook cell in which the plotting function is called, you should set `show=False`:

```
fig = sc.pl.dotplot(adata,var_names,show=False)
ax = fig.axes[0]
ax.set_xlabel('test')
```

2020-04-11 14:57 UTC, flying-sheep commented
Nothing here returns tuples of `(Figure, Axes)`.

Plotting functions usually either return a single axes object (if `show=False`) or a figure if `return_fig=True`.

2020-04-11 14:59 UTC, flying-sheep requested changes
I think it would be better if this behaved the way all plotting functions behave:

They usually either return a single Axes object (if `show=False`) or a Figure object if `return_fig=True`.

2020-05-06 18:43 UTC, z5ouyang commented
Any updates on this? scanpy=1.4.6 is still not to return matplotlib figure but still GridSpec even with "show=False". Or is there any other way to modify the figure/ax and save it after?
Thanks!

2020-05-12 10:44 UTC, fidelram commented
I am trying to address this and other issues in https://github.com/theislab/scanpy/pull/1127

In the new implementation, a dictionary of axes is returned.

2020-06-30 07:44 UTC, fidelram commented
After PR #1210 this is now possible for `dotplot`, `matrixplot` and `stacked_viloin` in master.  See [here](https://github.com/theislab/scanpy/pull/1210#issuecomment-641129949) for an example.

Using `show=False` returns a dictionary of axes and an axis can be passed to the plots.

2020-06-30 07:44 UTC, closed without merging