Addresses hashsolo pre_existing_cluster bugs
scverse/scanpy pull request #1483
Opened 2020-11-03 17:59 UTC by njbernstein

Also added a check to make sure the number of noise barcodes is less than the number of sample barcodes.

Fixed the example in the doc string to include the cell_hashing_columns argument

2020-11-03 18:09 UTC, njbernstein commented
https://github.com/theislab/scanpy/issues/1482

2020-11-04 23:15 UTC, adamgayoso commented
@njbernstein I had also noticed hashsolo wasn't added to the documentation, which you can do by adding `pp.hashsolo` [here](https://github.com/theislab/scanpy/blob/master/scanpy/external/__init__.py). Though I'm unsure which heading it belongs under.

2020-11-05 00:09 UTC, njbernstein commented
@adamgayoso  I don't think it fits under the other preprocessing tool headings of Data integration or Imputation.

Maybe add a new one called Call hashing or Sample demultiplexing. @fidelram thoughts? Not sure who else to tag

2020-11-09 06:05 UTC, adamgayoso commented
@ivirshup

2020-11-09 08:25 UTC, ivirshup commented
I think a new section would good here, maybe "Doublet detection"?

2020-11-09 18:08 UTC, njbernstein commented
@ivirshup I think doublet detection is a little too narrow in that we can also associate cells to the original sample they came from. Although many folks use cell hashing solely for the purpose of doublet detection. I'd prefer "Sample demultiplexing".

2020-11-12 10:50 UTC, ivirshup commented
I'd be happy with whatever, but it needs to go somewhere!

How about "Demultiplexing/ Doublet detection", so it can go with scrublet (#1476) in the next release, and potentially get split out later if more demultiplexing methods are added?

2020-11-16 20:17 UTC, njbernstein commented
Any advice for getting the docs to build? The link above doesn't give any details.

2020-11-18 02:29 UTC, adamgayoso reviewed
My comments will hopefully fix the docs

2020-11-18 02:29 UTC, adamgayoso commented on scanpy/external/__init__.py
> +.. autosummary::
add line between line 38 and 39

2020-11-18 02:29 UTC, adamgayoso commented on scanpy/external/__init__.py
> +~~~~~~~~~~~~~~~~
the tildes should extend to the end of doublet detection

2020-11-18 16:17 UTC, njbernstein commented
mm still not going. @adamgayoso sorry to bug ya again. or @ivirshup @fidelram is there a way to see why the docs are failing?

2020-11-19 06:01 UTC, ivirshup commented
Could you rebase on master? I can't see any info on the docs building since there are conflicts.

Can you build the docs locally?

2020-12-01 20:12 UTC, njbernstein commented
The docs build locally just fine. There are some warnings but it looks like they are from across the repo. Not sure why they are not building up here. The issue before was that I needed to remove typing from my docstrings. @adamgayoso @ivirshup

2020-12-13 06:34 UTC, ivirshup requested changes
Hey @njbernstein, it looks like headings want an empty line ahead of them

2020-12-13 06:34 UTC, ivirshup commented on docs/api/scanpy.plotting.rst
> +
```suggestion
```

2020-12-13 06:34 UTC, ivirshup commented on scanpy/external/pp/_hashsolo.py
>      -------
```suggestion
        To do operation in place

    Returns
    -------
```

2020-12-13 06:34 UTC, ivirshup commented on scanpy/external/pp/_hashsolo.py
>      Parameters
```suggestion
        More information and bug reports `here <https://github.com/calico/solo>`__.

    Parameters
```

2020-12-15 22:09 UTC, njbernstein commented
finally! Thank you @ivirshup

2020-12-17 04:47 UTC, ivirshup approved these changes
Great, thanks for fixing that!

2020-12-17 04:48 UTC, merged