Fix timeseries plot traceback
scverse/scanpy pull request #1654
Opened 2021-02-16 15:33 UTC by mvdbeek

2021-02-18 05:52 UTC, ivirshup requested changes
Thanks for the bugfix!

Could this get a test? It could be as simple as: 

* Create a small example that fails in current versions that works now
* Add a link to this PR so we know what issue this is testing for

Don't worry about the failing 3.6 build. That's unrelated.

2021-02-18 16:37 UTC, mvdbeek commented
I've added a test in https://github.com/theislab/scanpy/pull/1654/commits/189354eb0074140e3f2204d09b02aaa912d13934

2021-02-19 05:19 UTC, ivirshup approved these changes
Great, thanks for the PR! I've just changed how release notes are handled, so I'll manually add this note myself.

Could you comment here with what that release note should be?

2021-02-19 05:21 UTC, merged

2021-02-19 05:21 UTC, ivirshup commented
@meeseeksdev backport to 1.7.x

2021-02-19 08:35 UTC, mvdbeek commented
I guess the PR title would be fine ?