Fix passing of arguments between scrublet routines
scverse/scanpy pull request #1659
Opened 2021-02-18 10:53 UTC by pinin4fjords

Just a small PR to reinstate correct passing of parameters to Scrublet. Addresses https://github.com/theislab/scanpy/issues/1644.

2021-02-18 11:55 UTC, pinin4fjords commented
@ivirshup - looks like something cryptic going on here with the Scrublet code, it's also affecting https://github.com/theislab/scanpy/pull/1657 so it's nothing to do with the changes in this PR. Seems to be something new, to do with annoy and its [behaviour on certain processors](https://www.bountysource.com/issues/91392758-initializing-an-annoyindex-crashes-on-amd-processors) in the CI. 

I'm looking into it, but any bright ideas?

2021-02-18 12:04 UTC, pinin4fjords commented
I've come across this in [other places](https://github.com/conda-forge/hnswlib-feedstock/pull/11#issuecomment-779420118) recently, it's something to do with 'AVX instruction sets' in CI setups, but I'm a bit out of my depth there.

2021-02-18 13:51 UTC, pinin4fjords commented
Never mind, just turned off the problem option for the purpose of the tests :-)

2021-02-19 03:08 UTC, ivirshup approved these changes
Looks good to me, thanks for the quick fix!

One possible addition, up to you. Would you like to expand the tests so argument handling is more thoroughly covered? I'm not going to require this as I would for something in the main API, and I would ask that you take pains to make sure these tests don't take to long to run. It would be nice to know have assurances that arguments are being passed around correctly. 

The easiest way to do this would probably be "the results change when the arguments change".

2021-02-19 15:17 UTC, pinin4fjords commented
Okay, test added!

Couldn't test for use_approx_neighbors since we know from the above that one version of that breaks the CI. Also, 'stdev_doublet_rate' rate seems to have no impact, but I'm fairly sure it's passed correctly, so I'm going to blame the Scrublet code itself.

2021-02-21 06:05 UTC, ivirshup requested changes
Thanks for adding the test! Two things:

--------------

It's a bit slow:

![image](https://user-images.githubusercontent.com/8238804/108616956-71395100-7466-11eb-8bc1-8f30fa9d4454.png)
 
(from the `tests` tab of the azure pipeline). I've added a suggestion on how to cut this down. Basically: subset the anndata object first, gives about a 10X speed up, which is more inline with how long I'd be willing to give this.

--------------------------

I think it'd be better to test that the values changed than what printed changed. I've added a suggestion for testing that the values in the anndata objects are different after these runs.

2021-02-21 06:05 UTC, ivirshup commented on scanpy/tests/external/test_scrublet.py
> +    adata = sc.datasets.pbmc3k()
As written, this is the longest running test on our CI at 35 seconds.

Reducing the size of the data should make this go much faster.

```suggestion
    # Reduce size of input for faster test
    adata = sc.datasets.pbmc3k()[:500].copy()
    sc.pp.filter_genes(adata, min_counts=100)
```

2021-02-21 06:05 UTC, ivirshup commented on scanpy/tests/external/test_scrublet.py
> +        assert diff_result != default
Instead of testing the difference in what's printed, I'd like to test that the values changed.

```python
# For my suggestion, this will need to be added to imports
from anndata.tests.helpers import assert_equal
```

```suggestion
    default = sce.pp.scrublet(adata, use_approx_neighbors=False, copy=True)

    test_params = {
        'expected_doublet_rate': 0.1,
        'synthetic_doublet_umi_subsampling': 0.8,
        'knn_dist_metric': 'manhattan',
        'normalize_variance': False,
        'log_transform': True,
        'mean_center': False,
        'n_prin_comps': 10,
        'n_neighbors': 2,
        'threshold': 0.1,
    }

    # Test each parameter and make sure something changes

    for param in test_params.keys():
        test_args = {
            'adata': adata,
            'use_approx_neighbors': False,
            'copy': True,
            param: test_params[param],
        }
        curr = sc.external.pp.scrublet(**test_args)
        with pytest.raises(AssertionError):
            assert_equal(default, curr)
```

2021-02-22 09:17 UTC, pinin4fjords commented on scanpy/tests/external/test_scrublet.py
> +    adata = sc.datasets.pbmc3k()
Got it - thanks.

2021-02-22 09:20 UTC, pinin4fjords commented on scanpy/tests/external/test_scrublet.py
> +        assert diff_result != default
I was mostly interested in the least expensive/ fiddly way of checking the parameters were having an impact, and the STDOUT seemed to fit the bill (I did check that it remained identical with unchanged parameters). But obviously have no issues with this approach.

2021-02-22 09:43 UTC, ivirshup approved these changes
Thanks for the updates @pinin4fjords! LGTM

2021-02-22 09:44 UTC, pinin4fjords commented
> Thanks for the updates @pinin4fjords! LGTM

Thanks for the education / help. And for Scanpy of course :-)

2021-02-22 09:55 UTC, merged

2021-02-22 09:55 UTC, ivirshup commented
@Meeseeksdev backport to 1.7.x