I changed pheno_jaccard_ig to be a csr matrix so it is easier to save and manipulate - before it was a COO matrix which threw some errors.
scverse/scanpy pull request #2295
Opened 2022-07-18 16:01 UTC by dshefter

2022-07-27 22:10 UTC, Zethson commented
Hi,

could you please provide more details? What issues did you run into?

2022-10-11 08:26 UTC, dshefter commented
Hi,

The issues I was mostly running into were that when saving the anndata
variable as a h5ad file, 'pheno_jaccard_ig' was not compatible with this
action. So, I had to either remove pheno_jaccard_ig from the anndata object
and then save it as h5ad or convert it to a sparse matrix. This also
happened with a few other functions I tried on the anndata object, and I
kept getting the error "this function is not compatible with COO matrix
format", always talking about pheno_jaccard_ig. Therefore, since a sparse
matrix object does not have any problems with the functions I was running
on adata, changing pheno_jaccard_ig to a sparse matrix from the start makes
sense to circumvent any of those issues I was getting before.

I hope this makes sense.
Thank you,
Deena Shefter

On Wed, Jul 27, 2022 at 6:10 PM Lukas Heumos ***@***.***>
wrote:

> Hi,
>
> could you please provide more details? What issues did you run into?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scverse/scanpy/pull/2295#issuecomment-1197424392>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMILUOEK7J64GU3YOR7DB53VWGXULANCNFSM534YT5ZA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-15 17:20 UTC, adamgayoso requested changes

2023-02-15 17:20 UTC, adamgayoso commented on scanpy/external/tl/_phenograph.py
> +        adata.obsp[ig_key] = sp.sparse.csr_matrix(graph)
```suggestion
        adata.obsp[ig_key] = graph.tocsr()
```

2023-04-19 09:41 UTC, merged