allow sc.pp.subsampling in backed mode when returning a copy
scverse/scanpy pull request #2624
Opened 2023-08-18 09:02 UTC by eroell

Adresses issue #2495.

Suggested change to allow `sc.pp.subsample` in backed mode of AnnData, when `copy=True` in `sc.pp.subsample`

```
import scanpy as sc

adata = sc.read_h5ad("matrix/scatlas.h5ad", backed="r")
adata_sample = sc.pp.subsample(adata, fraction=0.01, copy=True)
```

2023-08-18 20:01 UTC, nleroy917 commented
Appreciate the PR - let me know if I can be of any assistance.

2023-08-24 11:20 UTC, ivirshup reviewed
Thanks for opening this!

What happens if the object is backed, but `copy=False`?

2023-08-24 11:36 UTC, eroell commented
Then the ValueError, which before occured for both `copy=False` and `copy=True`, is shown:
`ValueError: To copy an AnnData object in backed mode, pass a filename: '.copy(filename='myfilename.h5ad')'. To load the object into memory, use '.to_memory()'.`

2023-08-24 11:38 UTC, ivirshup commented
Could you throw a more informative error message for `copy=False`? Maybe:

`NotImplementedError("Inplace subsampling is not implemented for backed objects")`

?

2023-08-24 14:13 UTC, ivirshup requested changes
One minor change, I would invert the loops. I think it makes more sense to consider the `isbacked` cases together. So:

```python
if data.isbacked:
    if copy:
        return data[obs_indices].to_memory()
    else:
        raise NotImplementedError(...)
else:
    if copy:
        ...
```

Otherwise looking good! One minor change in the tests.

2023-08-24 14:13 UTC, ivirshup commented on scanpy/tests/test_preprocessing.py
> +    assert np.allclose(
```suggestion
    np.testing.assert_array_equal(
```

* The np.testing functions can give better error messages
* I think these should be equal, not just close

2023-08-24 14:40 UTC, ivirshup approved these changes
Looks great, thanks!

2023-08-24 14:48 UTC, merged