Allow blank issues
scverse/scanpy pull request #2868
Opened 2024-02-20 12:29 UTC by ivirshup

Sometimes the templates just don't fit

2024-02-20 12:48 UTC, flying-sheep commented
in which cases?

2024-02-20 13:50 UTC, ivirshup commented
Mostly dev process and tracking issues

2024-02-20 16:30 UTC, flying-sheep commented
Which are done by us exclusively, so we can just delete the template.

I’d also be OK to just do the first line of the diff, but leave out the ability for users to have a clickable thing.

Then we can just remove the `/choose` from the URL to get a blank form.

2024-02-20 16:31 UTC, flying-sheep requested changes
I’d also be OK to just do the first line of the diff, but leave out the ability for users to have a clickable thing.

Then we can just remove the `/choose` from the URL to get a blank form.

2024-02-20 16:31 UTC, flying-sheep commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: For things that don't quite fit elsewhere. Please note that other templates should be used in most cases – this is mainly for use by the developers.
```suggestion
```

2024-02-23 09:09 UTC, flying-sheep approved these changes
OK, this is relatively hidden and not a green button, so it’s fine

2024-02-23 09:09 UTC, merged