Updated missing params in docstrings
scverse/scanpy pull request #2888
Opened 2024-02-23 19:50 UTC by Steve-Cheney

Howdy y'all, working on a tool to convert packages to JSON and noticed there were some functions missing their parameters in the docstring. I've updated a few that were missing for better pydoc accessibility. All param descriptions were either copied from other similar param or made based on their functionality.

- [ ] Tests included or not required because:

Docstring updates only

- [ ] Release notes not necessary because:

No changes to logic

2024-02-23 19:54 UTC, Steve-Cheney commented
pre-commit.ci autofix

2024-02-27 13:18 UTC, flying-sheep commented
Nice!

One thing: the `ScanpyConfig` class isn‘t supposed to be instantiated by users, so it shouldn’t have a `Parameters` block.

So please revert this part. Otherwise this looks great, thank you.

2024-02-27 13:23 UTC, flying-sheep requested changes

2024-02-27 13:23 UTC, flying-sheep commented on scanpy/_settings.py
> +        Directory where the function scanpy.write writes to by default.
```suggestion
```

2024-02-27 17:22 UTC, Steve-Cheney commented
Done @flying-sheep !

2024-06-03 10:30 UTC, flying-sheep approved these changes

2024-06-03 11:41 UTC, merged