Doc submodule
scverse/scanpy pull request #2901
Opened 2024-03-12 11:30 UTC by ivirshup

2024-03-18 15:32 UTC, ivirshup commented
@flying-sheep, docs are building now if you want to take a look

2024-03-18 16:50 UTC, flying-sheep commented on docs/tutorials/basics/clustering-2017.ipynb
What are these? symlinks?

Why don’t we adapt the structure of the tutorials repo to how things are supposed to be?

2024-03-18 16:50 UTC, flying-sheep commented on docs/_tutorials.md
is there a redirect fot this in place?

2024-03-18 16:50 UTC, flying-sheep commented on docs/references.bib
> +  author    = {Stuart, Tim and Butler, Andrew and Hoffman, Paul and Hafemeister, Christoph and Papalexi, Efthymia and Mauck, William M and Hao, Yuhan and Stoeckius, Marlon and Smibert, Peter and Sati
Seems like the name formats aren’t consistent. The order is neither. Maybe we should run [Bibtool](https://github.com/ge-ne/bibtool) on it to make sure things are formatted consistently and errors can be spotted?

Running it in CI would be better, but it doesn’t seem to have releases unbundled from TeXLive, which might be a bit big to install in CI.

2024-03-18 16:50 UTC, flying-sheep commented on docs/how-to/index.md
> +This section contains short examples on how to perform specific tasks with scanpy.
So there’s where that went!

2024-03-18 19:04 UTC, ivirshup commented on docs/references.bib
> +  author    = {Stuart, Tim and Butler, Andrew and Hoffman, Paul and Hafemeister, Christoph and Papalexi, Efthymia and Mauck, William M and Hao, Yuhan and Stoeckius, Marlon and Smibert, Peter and Sati
I don't feel strongly about this, and am happy to take whatever cite key is given so long as it doesn't conflict.

I do feel strongly that I don't want to have a manual task beyond "is that info right" for bibtex entries.

2024-03-18 19:04 UTC, ivirshup commented on docs/tutorials/basics/clustering-2017.ipynb
This gives us a lot more flexibility in how we structure the docs. E.g. this makes it easy to have the "How To" section.

The main reason we have a notebooks repo is that executed notebooks are big. For notebooks that we can execute on the fly, they can just live directly in this repo.

Then, why should the URL for a tutorial be based on how we can render it?

2024-03-18 19:06 UTC, ivirshup commented on docs/_tutorials.md
No, but this  doesn't work on the stable docs:

https://scanpy.readthedocs.io/en/stable/_tutorials.html

2024-03-19 10:16 UTC, flying-sheep commented on docs/tutorials/basics/clustering-2017.ipynb
What do you think about this:

1. we move all notebooks into the notebook repo
2. we configure its CI to run the small ones on the fly in PRs (so no broken notebooks get merged in)
3. In the scanpy repo, we could run them in CI again (as tests)

2024-03-19 10:16 UTC, flying-sheep commented on docs/references.bib
> +  author    = {Stuart, Tim and Butler, Andrew and Hoffman, Paul and Hafemeister, Christoph and Papalexi, Efthymia and Mauck, William M and Hao, Yuhan and Stoeckius, Marlon and Smibert, Peter and Sati
Oh, I’m not talking about cite keys, but `author` names.

2024-03-19 11:12 UTC, ivirshup commented on docs/tutorials/basics/clustering-2017.ipynb
> we configure its CI to run the small ones on the fly in PRs (so no broken notebooks get merged in)

I'd rather not have to make sure the configs + CI are kept in sync. I think doing most of the CI on this side should be fine.

Plus if a broken PR merges there, it wouldn't effect the doc build here since the submodule should be pointing to a previous commit.

I would like to have "paired" PRs like we do for the template repo.

2024-03-19 11:13 UTC, ivirshup commented on docs/references.bib
> +  author    = {Stuart, Tim and Butler, Andrew and Hoffman, Paul and Hafemeister, Christoph and Papalexi, Efthymia and Mauck, William M and Hao, Yuhan and Stoeckius, Marlon and Smibert, Peter and Sati
But we can't run `bibtool` in pre-commit due to deps, right?

2024-03-19 12:11 UTC, ivirshup commented on docs/references.bib
> +  author    = {Stuart, Tim and Butler, Andrew and Hoffman, Paul and Hafemeister, Christoph and Papalexi, Efthymia and Mauck, William M and Hao, Yuhan and Stoeckius, Marlon and Smibert, Peter and Sati
Can you do the bib tool stuff on another branch?

2024-03-19 16:33 UTC, flying-sheep commented on docs/tutorials/basics/clustering-2017.ipynb
So for each PR that modifies one of the notebooks that are run in CI here, we need to manually make sure that there’s a paired PR that points to the same commit and makes sure CI runs here? Or we risk “breaking” CI here (read: having to debug things later when maybe multiple breakages have accumulated)?

I’m … not a fan. We have working CI for each commit in the other repo. Sure, notebooks are never run and we need to fix that, but there will never be breakage when pointing scanpy to a new commit there. I like that about our current solution, let’s keep that aspect.

2024-03-19 17:02 UTC, ivirshup commented on docs/tutorials/basics/clustering-2017.ipynb
> we need to manually make sure that there’s a paired PR that points to the same commit and makes sure CI runs here?

We automated this for the template repo, couldn't we do the same here?

2024-03-20 12:47 UTC, flying-sheep commented on docs/tutorials/basics/clustering-2017.ipynb
We could, sure. It's just much more complicated than just running the CI on one side and then using the artifacts from successful CI runs (which is what we do now by linking them).

2024-03-20 16:30 UTC, flying-sheep requested changes
Seems like you accidentally force-pushed over my commits, please re-add: https://github.com/scverse/scanpy/compare/c1d042aaf0a12ecc2da4ee5af290fcfca6bb53b1..b39ce21e57e6ffcfd70a6531a9b105642df0d86f

2024-03-22 10:10 UTC, flying-sheep requested changes
The structure looks good, two main things:

1. The tutorial site looks a bit messy, with toc trees, paragraphs, and images interspersed. If you e.g. remove the sub-indices, put the text together and use a sphinx-design grid for the images, you’d get:

   ![grafik](https://github.com/scverse/scanpy/assets/291575/afe216fa-ca9e-45a5-9b32-2eeea3fecdc0)


3. See https://github.com/scverse/scanpy/pull/2901#pullrequestreview-1949433456

   Bibtool should run either in CI or at least locally.

2024-03-22 10:10 UTC, flying-sheep commented on pyproject.toml
> +    "sphinxcontrib-bibtex",
```suggestion
    "sphinxcontrib-bibtex",
    "setuptools",  # https://bitbucket.org/pybtex-devs/pybtex/issues/169
```

2024-03-22 10:10 UTC, flying-sheep commented on docs/news.md
> +[`rapids-singlecell`](https://rapids-singlecell.readthedocs.io/en/latest/) by Severin Dicks provides a scanpy-like API with accelerated operations implemented on GPU.
Please don’t use inline links

```suggestion
[`rapids-singlecell`][] by Severin Dicks provides a scanpy-like API with accelerated operations implemented on GPU.

[`rapids-singlecell`]: https://rapids-singlecell.readthedocs.io/en/latest/
```

2024-03-22 10:10 UTC, flying-sheep commented on docs/tutorials/basics/index.md
Should this page (and `experimental/index.md`) exist? `tutorials/index.md` already renders full toc trees of these sections, so the sub-pages just contain duplicate information.

2024-03-22 13:36 UTC, ivirshup commented on docs/tutorials/basics/index.md
I believe these are required so we get the full TOC on the higher pages

2024-03-22 13:36 UTC, ivirshup commented on docs/news.md
> +[`rapids-singlecell`](https://rapids-singlecell.readthedocs.io/en/latest/) by Severin Dicks provides a scanpy-like API with accelerated operations implemented on GPU.
Why?

2024-03-22 13:51 UTC, ivirshup commented
> Seems like you accidentally force-pushed over my commits, please re-add:

This was intentional as those changes broke the doc build. sphinxcontrib-bibtex couldn't parse the reformatted bibtex file. Over [here](https://github.com/scverse/scanpy/pull/2901#discussion_r1530244562) I requested that if you want to add bib tool working as a precommit, I would like you to do it in a separate branch.

2024-03-22 13:56 UTC, ivirshup commented on pyproject.toml
> +    "sphinxcontrib-bibtex",
I'm not sure I understand this request. I get that there is some upstream bug causing failures on someone else's CI, but we don't seem to be triggering that here?

2024-03-22 15:11 UTC, flying-sheep commented on docs/news.md
> +[`rapids-singlecell`](https://rapids-singlecell.readthedocs.io/en/latest/) by Severin Dicks provides a scanpy-like API with accelerated operations implemented on GPU.
Don’t do inline links, they make text less readable.

2024-03-22 19:11 UTC, ivirshup commented on docs/news.md
> +[`rapids-singlecell`](https://rapids-singlecell.readthedocs.io/en/latest/) by Severin Dicks provides a scanpy-like API with accelerated operations implemented on GPU.
I'm not sure I agree. Maybe for really long links. But: 

* there's no effect on readability when rendered
* you have to think about link targets and whether they are already defined
* I don't know if these are handled by sphinx, but we've had issues in the past with sphinx defining reference targets globally and having subtle changes or typos mean we link to the wrong thing. It's harder to get inline links wrong.
* There are 22 links on this page currently, 20 are inline.

2024-03-22 19:16 UTC, ivirshup commented on docs/tutorials/basics/index.md
If there is a better way, I'm up for it. But I couldn't figure it out.

2024-03-22 19:55 UTC, ivirshup commented on docs/tutorials/basics/index.md
I would like to have something like what squidpy has here: 
https://squidpy.readthedocs.io/en/latest/notebooks/examples/index.html#

However, I'm not sure if there's a difference in configuration or the pydata theme just doesn't allow this with the way it splits the TOC to either side of the screen (which I am coming to think is actually bad and difficult to use, it just looks nice)

2024-03-25 09:03 UTC, flying-sheep commented on pyproject.toml
> +    "sphinxcontrib-bibtex",
Our CI comes with setuptools preinstalled, but that’s not a given. `pip install scanpy[doc]` will only be guaranteed to install all runtime dependencies if we add it here.

2024-03-25 09:05 UTC, flying-sheep commented on docs/news.md
> +[`rapids-singlecell`](https://rapids-singlecell.readthedocs.io/en/latest/) by Severin Dicks provides a scanpy-like API with accelerated operations implemented on GPU.
That’s horrible, we should fix that. Did the MyST conversion do that?

2024-03-25 09:12 UTC, flying-sheep commented on docs/tutorials/basics/index.md
I don’t understand why the split TOC is supposed to mandate that, could you explain?

Also squidpy has the `notebooks` submodule under the `docs` folder, we should do that too.

2024-03-25 09:45 UTC, flying-sheep commented on docs/news.md
> +[`rapids-singlecell`](https://rapids-singlecell.readthedocs.io/en/latest/) by Severin Dicks provides a scanpy-like API with accelerated operations implemented on GPU.
Intersphinx:

```rst
:doc:`rapids_singlecell:index`
```

2024-03-25 10:15 UTC, ivirshup commented on docs/tutorials/basics/index.md
* https://github.com/executablebooks/sphinx-book-theme/issues/337

2024-03-25 10:37 UTC, flying-sheep commented on pyproject.toml
> -
I put that blank line there intentionally, because you got confused one time and added a warning filter in the middle of the error block.

2024-03-25 10:50 UTC, flying-sheep commented on docs/tutorials/basics/index.md
So we would need to override `sphinx_book_theme/components/sbt-sidebar-nav.html` somehow? They don’t document how to do that.

2024-03-25 12:51 UTC, flying-sheep commented
OK, now the only thing missing is to make sure the bibtex isn’t a mess.

You said you don’t want to do that manually, so please add some way to do it automatically.

> sphinxcontrib-bibtex couldn't parse the reformatted bibtex file. 

hmm, so we can’t trust its parser to work properly, that’s a bit concerning. But we control what it sees so that isn’t too bad.

2024-03-26 13:01 UTC, ivirshup commented
> OK, now the only thing missing is to move the notebooks directory into docs 

We have already discussed this, and it is staying as is for now. We can think about doing this in the future, but please make your case in an issue.

> bibtex isn’t a mess.

I will be leaving the bibtex as is, I don't see an issue with the bibtex as it renders fine. As I requested last week, you can suggest a formatter for it in a separate PR. Notably this bibtex is copied directly from scverse-tutorials, which doesn't seem to have caused any issues.

FWIW there are some tools for working with bibtex recommended here:

* https://github.com/ge-ne/bibtool/issues/58
  * bibtex-tidy has a pre-commit that doesn't do exactly what you're looking for
  * python-bibtexparser seems like it'd be able to do what you want, and is far more actively maintained than bibtool.

2024-03-26 13:15 UTC, merged