bbknn and leiden functions
scverse/scanpy pull request #361
Opened 2018-11-13 13:33 UTC by ktpolanski

- created `bbknn.py` and `leiden.py`
- added Park18 and Traag18 references
- added bbknn import to `api/pp.py` and leiden import to `api/tl.py`

2018-11-13 14:18 UTC, ktpolanski commented
Think the Travis thing failing is because of the new dependencies

2018-11-13 14:25 UTC, flying-sheep requested changes
Sure is `E   ImportError: No module named 'leidenalg'`

You should add a new `extra` in setup.py:

https://github.com/theislab/scanpy/blob/04056e4798873ecec71adcc51804825245a55295/setup.py#L26

then install it in `.travis.yml` (`pip install -e .[louvain,leiden,test]` or so) and add a test.

2018-11-13 14:25 UTC, flying-sheep commented on scanpy/tools/leiden.py
> +import leidenalg
You should move this inside of the function:

```py
def leiden(...):
    import leidenalg
```

2018-11-13 14:32 UTC, ktpolanski commented on scanpy/tools/leiden.py
> +import leidenalg
Will this make it not fail?

2018-11-13 14:45 UTC, ktpolanski commented on scanpy/tools/leiden.py
> +import leidenalg
Oh would you look at that it doesn't fail anymore. Problem solved, thanks!

2018-11-13 15:50 UTC, flying-sheep commented
The tests don’t fail, but you should still add the extra to setup.py

2018-11-13 16:02 UTC, ktpolanski commented
> The tests don’t fail, but you should still add the extra to setup.py

Is the fact that you don't list `'docs'` in your pip thing (`pip install -e .[louvain,leiden,test]`) purposeful?

2018-11-13 16:09 UTC, flying-sheep commented
Yes. We don’t build the docs, we just check the readme. so we only need docutils and not sphinx and so on.

2018-11-13 16:31 UTC, ktpolanski commented
Ok, I've added the thing to `setup.py`, and did the `pip` command with all non-docs extras, but apparently the travis file didn't change.

2018-11-13 17:08 UTC, flying-sheep commented
Currently there are no tests, so those packages aren't actually needed. Looks good to me!

2018-11-15 09:44 UTC, ktpolanski commented
...so, what's the procedure with this? Do I need to do anything else?

2018-11-15 11:39 UTC, flying-sheep requested changes
Almost done! Sorry for the delay

2018-11-15 11:39 UTC, flying-sheep commented on scanpy/preprocessing/bbknn.py
> +	Batch balanced KNN, altering the KNN procedure to identify each cell's top neighbours in
This can be simplified I think. The whole file could just be:

```py
try:
    from bbknn import bbknn
except ImportError:
    def bbknn(*args, **kwargs):
        raise ImportError('Please install BBKNN: `pip3 install bbknn`')
```

Except if we want control over the docstring? But as long as the upstream docstring is good, why bother?

Also the file is tab-indented while the rest of scanpy is 4-space-indented. Please adapt it.

2018-11-15 11:39 UTC, flying-sheep commented on scanpy/tools/leiden.py
> +    '''
Please use `"""`

2018-11-15 11:39 UTC, flying-sheep commented on scanpy/tools/leiden.py
> +        adata,
can you please add typing here instead of putting it in the docstring? we’re moving to typehints:

```py
def leiden(
    adata: AnnData,
    key_added: str = 'leiden',
    ...
    adjacency: Optional[sparse.spmatrix] = None,
    ...
```

And in the docs just:

```rst
Parameters
----------
adata
    The annotated data matrix.
key_added
    ``adata.obs`` key under which to add the cluster labels.
...
```

2018-11-15 11:39 UTC, flying-sheep commented on scanpy/tools/leiden.py
> +    #are we clustering a user-provided graph or the default AnnData one?
Please use PEP8 style `# comment`, not `#comment`

2018-11-15 16:25 UTC, ktpolanski commented
I tried to do the things. I have no idea how to type the arguments, so there may be some trainwrecks there. Funny how it wasn't like that in the louvain function I based this on.

2018-11-15 16:28 UTC, ktpolanski commented
So apparently this now fails on the typing, on a line you provided as an example. Great. Can I please revert to how it was?

2018-11-15 16:35 UTC, flying-sheep commented
Hi! Sorry for frustrating you :( if you want I can fix and merge it manually. You're doing great work!

You simply need to import the things you're using in the annotations, then it'll work!

2018-11-15 16:36 UTC, ktpolanski commented
This will introduce a new problem, won't it? I'm using some sort of thingy from leiden

2018-11-15 16:47 UTC, ktpolanski commented
Ok, I'm stumped. Help please.

2018-11-15 19:30 UTC, flying-sheep commented
just leave that one parameter’s annotation out for now, and I’ll pull it :wink:

2018-11-16 08:55 UTC, ktpolanski commented
Ok, did that. Sorry about the trouble, that was my first time trying to type stuff and I was a bit in the dark on this. Thanks for your patience.

2018-11-16 09:09 UTC, merged

2018-11-16 09:09 UTC, flying-sheep commented
done. thank you!

2018-11-16 09:20 UTC, flying-sheep commented
I had to fix a few issues, if you want you can check it out: 66e64b40870035c3ee869e3baf34cf7110508d85

- I unified the parameter order with `louvain`
- I actually import it in `sc.tl`
- I added it to the docs
- I added a test
- I fixed the references
- You did this:

    ```py
    partition_kwargs['weights'] = None
    if use_weights:
        weights = np.array(g.es['weight']).astype(np.float64)
    ```

    But I assume you meant this. Am I correct?

    ```py
    if use_weights:
        partition_kwargs['weights'] = np.array(g.es['weight']).astype(np.float64)
    ```

2018-11-16 09:23 UTC, ktpolanski commented
Good catch, sorry! I added the whole `partition_kwargs` dictionary late into the process and forgot to change that syntax.

In that case, could you also "hook up" `pp.bbknn`?

2018-11-16 09:24 UTC, flying-sheep commented
Good call, will do!

2018-11-19 01:15 UTC, falexwolf commented
Thank you, @flying-sheep for fielding all the questions! Thank you for the PR, @ktpolanski! Is there anything still unclear where I can be of help?

2018-11-19 08:21 UTC, flying-sheep commented
Well, the bbknn docs look like this: https://scanpy.readthedocs.io/en/latest/api/index.html#batch-effect-correction

I went that way since I didn’t want to make it look like we coded it (with the docs hosted on our page and so on). Do you think that’s a good solution or would you like it to be done differently?

2018-11-19 08:56 UTC, ktpolanski commented
I mirrored the scanpy docstring style to the best of my ability, but for some reason it turned out a little bit different visually than the ones you have. Hope that's not too much of a problem.

2018-11-19 09:39 UTC, flying-sheep commented
Surely not! And since we’re linking it anyway, it doesn’t need to match ours.

I like that you’re using ``` ``code`` ``` instead of ``` `code` ```, that looks much better than the way many many docstrings in scanpy do.

I suggest that you add some lines to your intersphinx mapping and use more links instead of code though, that makes the docs easier to use, since people can just click on things:

https://github.com/theislab/scanpy/blob/7b97d0d734970527230cf7f25ab15df874a143b3/docs/conf.py#L60-L69

I also added this hack to make links to `AnnData` and `csr_matrix` work:

https://github.com/theislab/scanpy/blob/7b97d0d734970527230cf7f25ab15df874a143b3/docs/conf.py#L236-L253

2018-11-19 10:14 UTC, falexwolf commented
```
try:
    from bbknn import bbknn
except ImportError:
    def bbknn(*args, **kwargs):
        raise ImportError('Please install BBKNN: `pip3 install bbknn`')
```

> I went that way since I didn’t want to make it look like we coded it (with the docs hosted on our page and so on). Do you think that’s a good solution or would you like it to be done differently?

This is great!

https://scanpy.readthedocs.io/en/latest/api/scanpy.api.pp.bbknn.html#scanpy.api.pp.bbknn

But I actually don't see any docs there, I don't know why it doesn't find the original docstring... We'd like to have the reference to @ktpolanski preprint in the docstring in the first line together with a short summary of what it does and how it does it, just as for any other function. As this directly uses the implementation from @ktpolanski, we'd also want an explicit statement about that.

> pp.bbknn is just an alias for bbknn.bbknn(). Refer to it for the documentation.

... can be removed. That should be evident...

In the case of the `tl.leiden` wrapper, I'd also add an explicit statement that this wraps the leiden package of Traag (2018).

Otherwise, all of this is great!

2018-11-19 11:06 UTC, flying-sheep commented
> But I actually don't see any docs there, I don't know why it doesn't find the original docstring...

That’s because on readthedocs, bbknn isn’t installed, so it uses the dummy version.

> We'd like to have the reference to @ktpolanski preprint in the docstring in the first line together with a short summary of what it does and how it does it, just as for any other function.

We could do that either by adding a docstring to the dummy version that links to https://bbknn.rtfd.io or by installing bbknn on rtd, and modifying the docstring programmatically. something like:

```py
try:
    from bbknn import bbknn
    1st_para, rest = bbknn.__doc__.split('\n', 1)
    bbknn.__doc__ = '''

For a graphical explanation, visit `The bbknn project <https://github.com/Teichlab/bbknn>`__.

'''.format(1st_para, rest)
except ImportError:
    ...