Add ability to run nearest neighbors, umap and louvain on a GPU using RAPIDS
scverse/scanpy pull request #830
Opened 2019-09-11 14:58 UTC by tomwhite

This adds RAPIDS as an (experimental) option for running some of the graph algorithms on a GPU.

Example usage is demonstrated here: https://github.com/tomwhite/scanpy_usage/tree/rapids-gpu/1909_rapids_gpu

In summary:

```python
    sc.pp.neighbors(adata, method='rapids')
    sc.tl.louvain(adata, flavor='rapids')
    sc.tl.umap(adata, method='rapids')
```

Timings (on 130K samples):

| Step      | CPU time (s) | GPU time (s) | Speedup |
| --------- | ------------ | ------------ | ------- |
| Neighbors | 47           | 15           | 3x      |
| Louvain   | 70           | 1            | 70x     |
| UMAP      | 186          | 15           | 12x     |

Comments:
* In general the output figures are quite different for each of the algorithms compared to regular Scanpy. (See the figures in the link above.)
* RAPIDS uses exact nearest neighbors (using https://github.com/facebookresearch/faiss I think), whereas the default NNDescent algorithm in Scanpy is approximate.
* Louvain community detection results in a different number of communities (28 vs 45). I'm not sure if it is possible to change the termination criteria or other parameters that would make the two outputs the same, or at least more similar.
* UMAP is different too, and in particular it is bunched in one corner. There are a few very small clusters in the opposite corner, which looks like it might be a bug.
* UMAP computes the nearest neighbors again from scratch - it can’t reuse the ones computed earlier since RAPIDS only exposes the fit/transform methods, and not `simplicial_set_embedding` that regular UMAP exposes.
* In general it would be useful to understand what random number generators each of the alternatives use, how they can be controlled, and what prospects there are for achieving identical output (if any).
* This is using RAPIDS version 0.7 since it is the version available on the Google Cloud image I used (https://cloud.google.com/deep-learning-vm/docs/images).

2019-09-12 11:50 UTC, flying-sheep commented
Wow, nice, those are some impressive speedups!

2019-09-24 07:52 UTC, flying-sheep commented
I think this looks good and simple enough. Could you please fix the CI errors?

Also there’s 3 added optional deps: cuml, cudf, and cugraph. I assume they’re all different CUDA packages. Could you add them into an `extra` in setup.py?

The RAPIDS umap branch doesn’t use a metric argument. Does it support metrics other than euclidean?

2019-09-25 10:57 UTC, tomwhite commented
> The RAPIDS umap branch doesn’t use a metric argument. Does it support metrics other than euclidean?

No, it only supports Euclidean distance currently.

2019-09-25 11:41 UTC, tomwhite commented
@flying-sheep thanks for taking a look. I've fixed the CI errors now and added the deps as suggested.

2019-09-25 14:28 UTC, flying-sheep requested changes
OK, great! I addressed the metric problem in some suggestions.

Do you think testing this on Travis is possible (i.e. running this on a CPU) or do the packages *need* a GPU?

I’d also like to ask you to add the dependencies to a `rapids` extra in setup.py:

https://github.com/theislab/scanpy/blob/b9dbe36b3e9c52a3c793af991c9cd7c78db9f92a/setup.py#L30-L33

If tests are possible, we need to add some and add the `rapids` extra to the list of test extras:

https://github.com/theislab/scanpy/blob/b9dbe36b3e9c52a3c793af991c9cd7c78db9f92a/.travis.yml#L20

2019-09-25 14:28 UTC, flying-sheep commented on scanpy/neighbors/__init__.py
> +        if not use_dense_distances or method == 'umap' or method == 'rapids':
```suggestion
        if not use_dense_distances or method in {'umap', 'rapids'}:
```

2019-09-25 14:28 UTC, flying-sheep commented on scanpy/neighbors/__init__.py
> +        if method not in {'umap', 'gauss', 'rapids'}:
```suggestion
        if method == 'rapids' and metric != 'euclidean':
            raise ValueError("`method` 'rapids' only supports the 'euclidean' `metric`.")
        if method not in {'umap', 'gauss', 'rapids'}:
```

2019-09-25 14:28 UTC, flying-sheep commented on scanpy/tools/_umap.py
> +    method : {{'umap', 'rapids'}}  (default: `'umap'`)
This function doesn’t use `@doc_params`, so normal braces should be sufficient.

```suggestion
    method : {`'umap'`, `'rapids'`}  (default: `'umap'`)
```

2019-09-25 14:28 UTC, flying-sheep commented on scanpy/tools/_umap.py
> +    elif method == 'rapids':
Maybe a warning would be enough here?

```suggestion
    elif method == 'rapids':
        metric = neigh_params.get('metric', 'euclidean')
        if metric != 'euclidean':
            raise ValueError(
                f'`sc.pp.neighbors` was called with `metric` {metric!r}, '
                "but umap `method` 'rapids' only supports the 'euclidean' metric."
            ) 
```

2019-09-25 14:28 UTC, flying-sheep commented on scanpy/neighbors/__init__.py
> +            raise ValueError('`method` needs to be \'umap\', \'gauss\', or \'rapids\'.')
```suggestion
            raise ValueError("`method` needs to be 'umap', 'gauss', or 'rapids'.")
```

2019-09-25 15:57 UTC, tomwhite commented
The packages do need a GPU, unfortunately. There is no way to fallback to run on a CPU, so I don't think Travis can test them.

2019-09-25 16:30 UTC, flying-sheep approved these changes

2019-09-25 16:31 UTC, merged

2019-09-25 16:31 UTC, flying-sheep commented
OK, too bad …