Add trimap to scanpy
scverse/scanpy pull request #862
Opened 2019-10-07 18:37 UTC by eamid

TriMap: Large-scale Dimensionality Reduction Using Triplets

TriMap is a dimensionality reduction method that uses triplet constraints to form a low-dimensional embedding of a set of points. The triplet constraints are of the form "point i is closer to point j than point k". The triplets are sampled from the high-dimensional representation of the points and a weighting scheme is used to reflect the importance of each triplet.

TriMap provides a significantly better global view of the data than the other dimensionality reduction methods such t-SNE, LargeVis, and UMAP. The global structure includes relative distances of the clusters, multiple scales in the data, and the existence of possible outliers. We define a global score to quantify the quality of an embedding in reflecting the global structure of the data. Also, TriMap is significantly faster than t-SNE, LargeVis, and UMAP and scales better to large datasets.

paper: https://arxiv.org/abs/1910.00204

code: https://github.com/eamid/trimap

2019-10-09 13:40 UTC, fidelram commented
Thanks for this contribution! Can you look at the travis errors? See https://github.com/theislab/scanpy/pull/797#issuecomment-536861482 for background.

To fix formatting errors you can use https://github.com/psf/black

Furthermore, can you add a small example to the docstring? (see for example: https://github.com/theislab/scanpy/blob/master/scanpy/external/tl/_palantir.py)

2019-10-09 13:47 UTC, LuckyMD commented
I guess this should probably be added to scanpy external as other external packages are?

2019-10-09 14:17 UTC, fidelram commented
@LuckyMD I agree.

2019-10-11 18:29 UTC, eamid commented
Thanks for getting back to me. I fixed the formatting errors and moved trimap to scanpy external. 
trimap is no longer imported by default, so the overall import time is unaffected. 
I also added an example to the docstring.

Please let me know if further fixes are required.

2019-12-03 01:52 UTC, eamid commented
I fixed the merge  conflicts, it should be good to go!

2019-12-03 06:17 UTC, eamid commented
I fixed the merge conflicts. Hope it is all good now!
Please let me know if you need more changes.

2019-12-04 18:10 UTC, flying-sheep commented on scanpy/external/exporting.py
> +        `"fa"`, `"fr"`, `"kk"`, `"drl"`, `"rt"`, `"trimap"`].
Nice catch. @all: we should create this string using code, not by requiring people to find and update it.

2019-12-04 18:30 UTC, flying-sheep requested changes
Looks good apart from some details, and I liked the method when it saw it being presented a few months ago.

2019-12-04 18:30 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +):
Please add type hints here. Check other methods for how to do `metric` using `compat.Literal`.

Don’t forget the return type!

2019-12-04 18:30 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +    ------
Please call this section `Parameters`, use numpydoc style and get rid of “default” (it’s added automatically)

2019-12-04 18:30 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +    nearest-neighbor calculation (default = True)
I think the default should be `None`, which means “True, but throw a warning if we have to run sc.pp.pca”

2019-12-04 18:30 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +    with momentum, 'dbd': GD with momentum delta-bar-delta (default))
I don’t see this in the actual parameters, where is it?

Please sort the parameters like they appear in the function and make sure every documented one is also present and vice versa.

2019-12-04 18:30 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +    verbose: Print the progress report (default = True)
Please derive this from `sc.settings.verbosity` by default.

2019-12-04 18:30 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +    (default = False)
This parameter is also absent. If you conditionally want to return a non-AnnData, please replace “copy” with “inplace” (the semantics are “inplace=True” → modify “adata”, “inplace=False” → return a different data structure)

2019-12-04 18:30 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +    n_dims=2,
Please add a `*,` after `adata,` or `n_dims: int = 2,`.

This way we’re free to reorganize subsequent parameters without it being a breaking change.

2019-12-04 18:30 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +            '\'angular\', and \'hamming\'.'
please avoid unnecessary escaping and prefer f-strings to concatenating strings with `+`:

```py
f'Metric {metric!r} is currently not supported by trimap. '
'Acceptable values are {", ".join(map(repr, allowed_metrics))}'
```

2019-12-04 18:30 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +        deep=('added\n' "    'X_trimap', TriMap coordinates (adata.obsm)"),
```suggestion
        deep="added\n    'X_trimap', TriMap coordinates (adata.obsm)",
```

2019-12-04 20:42 UTC, eamid commented
Thanks @flying-sheep for the thorough feedback! I made the changes. There is still a Travis CI error about slow_to_import modules. Since trimap is now in external, I am now sure how this test is being affected.

2019-12-05 09:46 UTC, flying-sheep commented
Very weird. Importing `scipy.sparse` shouldn’t import `scipy.stats`, and you didn’t add any other imports. Could be that this is a change in some updated version of something.

Does the test fail for you? Then you could find out how it gets imported using `import-profiler`

2019-12-05 18:40 UTC, eamid commented
Thanks @flying-sheep! I haven't added any new imports other those for type hints and copying anndata: [https://github.com/eamid/scanpy/compare/9ae6c19...b7ed705](https://github.com/eamid/scanpy/compare/9ae6c19...b7ed705)

My previous commit passed the tests. Could this be because of recent commits on your side?

2019-12-06 03:17 UTC, gokceneraslan commented
I have the same issue here https://github.com/theislab/scanpy/pull/945, so it's not specific to this PR,fyi.

2019-12-06 11:58 UTC, flying-sheep commented
To help debug it, can one of you do what I suggested? I don’t have the problem locally and if one of you does see it, it would be much easier to find out which dependency started to import that module.

2019-12-06 12:05 UTC, flying-sheep requested changes
The PR looks really clean now, congrats!

One thing left I just realized: the bibtex code for the reference will look pitiful when rendered as reStructuredText. Can you please add yourself to `references.rst` and just cite yourself as `[Amid19]_` in the docstring instead of using that “Reference” section?

2019-12-06 17:36 UTC, eamid commented
Thank you @flying-sheep! All done.

2019-12-10 01:35 UTC, eamid commented
@flying-sheep just following up on the PR. Thanks!

2019-12-10 14:50 UTC, flying-sheep commented on scanpy/external/tl/_trimap.py
> +    **X_trimap** : `np.ndarray`, (`adata.obs`, shape=[n_samples, n_components], dtype `float`)
```suggestion
    **X_trimap** : :class:`~numpy.ndarray`, (:attr:`adata.obsm`, shape=(n_samples, n_components), dtype `float`)
```

One typo I missed.

2019-12-10 17:18 UTC, merged

2019-12-10 17:18 UTC, flying-sheep commented
Great, thank you!

2019-12-10 17:21 UTC, eamid commented
Thank you @flying-sheep!